BASE: ['inference_base.yaml']
TRAINING_TYPE: 'fine'


FINE_MODEL_PATH: "xx/checkpoint_pth/Demo_LargescaleCT_PETul_bigsegnet_CDA/" # The path of the downloaded checkpoint directory.
CHECK_POINT_NAME: "final_checkpoint.pth"
VAL_OUTPUT_PATH: "result/train-largescalect-test-pet" # The path of inference output directory.

DATASET:
  DATASET_NAME: 'inference_train-ct'
  VAL_IMAGE_PATH: "PET/PublicValidation/PET_imagesVal/"
  VAL_CHANGE_SPACING: False
  DA:
    DO_MIRROR: False
  FINE:
    SIZE: [ 96, 128, 128 ]
    PREPROCESS_SIZE: [ 128, 128, 96 ]


VAL:
  IS_CROP: False
  TTA: True
