BASE: ['inference_base.yaml']
TRAINING_TYPE: 'fine'


FINE_MODEL_PATH: "xx/checkpoint_pth/Demo_LargescaleCT_MRIul_bigsegnet_CDA/" # The path of the downloaded checkpoint directory.
CHECK_POINT_NAME: "final_checkpoint.pth"
VAL_OUTPUT_PATH: "result/test-mri" # The path of inference output directory.

DATASET:
  BASE_DIR: "/nfs/scratch/xjiangbh/FLARE/large-scale-data/"
  DATASET_NAME: 'inference_train-ct'
  VAL_IMAGE_PATH: "MRI/PublicValidation/MRI_imagesVal/"
  VAL_CHANGE_SPACING: False
  DA:
    DO_MIRROR: False
  FINE:
    SIZE: [ 96, 128, 128 ]
    PREPROCESS_SIZE: [ 128, 128, 96 ]
    
VAL:
  IS_CROP: False
  TTA: True
