BASE: ['inference_base.yaml']
TRAINING_TYPE: 'fine'

# VAL_OUTPUT_PATH: "result/train-ct-test-pet" # The path of inference output directory.

# FINE_MODEL_PATH: "/home/xjiangbh/FLARE_work/FLARE25-task3-LTUDA/checkpoint_pth/Demo_CT_MRIul_bigsegnet_CDA_250524_014254/" # The path of the downloaded checkpoint directory.
# CHECK_POINT_NAME: "final_checkpoint.pth"
# VAL_OUTPUT_PATH: "result/train-ctmriul-test-pet_CDA" # The path of inference output directory.

# FINE_MODEL_PATH: "/home/xjiangbh/FLARE_work/FLARE25-task3-LTUDA/checkpoint_pth/Demo_CT_MRIul_bigsegnet_fakemri_250526_141808/" # The path of the downloaded checkpoint directory.
# CHECK_POINT_NAME: "final_checkpoint.pth"
# VAL_OUTPUT_PATH: "result/train-ctfakemri-test-pet" # The path of inference output directory.

FINE_MODEL_PATH: "/home/xjiangbh/FLARE_work/FLARE25-task3-LTUDA/checkpoint_pth/Demo_LargescaleCT_bigsegnet_250526_173209/" # The path of the downloaded checkpoint directory.
CHECK_POINT_NAME: "final_checkpoint.pth"
VAL_OUTPUT_PATH: "result/train-largescalect-test-pet" # The path of inference output directory.

DATASET:
  DATASET_NAME: 'inference_train-ct'
  VAL_IMAGE_PATH: "PET/PublicValidation/PET_imagesVal/"
  VAL_CHANGE_SPACING: False
  DA:
    DO_MIRROR: False
  FINE:
    SIZE: [ 96, 128, 128 ]
    PREPROCESS_SIZE: [ 128, 128, 96 ]


VAL:
  IS_CROP: False
  TTA: True
