BASE: ['eval_base.yaml']
TRAINING_TYPE: 'fine'

VAL_OUTPUT_PATH: "result/test-mri" # The path of inference output directory.

DATASET:
  BASE_DIR: "/nfs/scratch/xjiangbh/FLARE/large-scale-data/"
  DATASET_NAME: "eval_train-ct"
  VAL_IMAGE_PATH: "MRI/PublicValidation/MRI_imagesVal/" # ground-truth MR
  VAL_MASK_PATH: 'MRI/PublicValidation/MRI_labelsVal'  # ground-truth MR label
  VAL_CHANGE_SPACING: False
  DA:
    DO_MIRROR: False
  FINE:
    SIZE: [ 96, 128, 128 ]
    PREPROCESS_SIZE: [ 128, 128, 96 ]
    
INFERENCE:
  IS_OVERWRITE_PREDICT_MASK: False
